name: CI - Raspbian Cross Compile

on:
  workflow_call: 
    inputs: 
      checkout_ref:
        description: "Use specific Tag, etc, for git checkout (default: release-5.1.1)"
        required: false
        type: string
        default: release-5.1.1

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        libt_version: ["2.0.11", "1.2.20"]
        qbt_gui: ["GUI=OFF"]
        qt_version: ["6.6.3"]
        appimage_arch: ["armhf"]

    env:
      boost_path: "${{ github.workspace }}/../boost"
      harden_flags: "-D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS"
      libtorrent_path: "${{ github.workspace }}/../libtorrent"

    steps:
      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.checkout_ref }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
            build-essential cmake ninja-build \
            libssl-dev libxkbcommon-x11-dev libxcb-cursor-dev zlib1g-dev

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          store_cache: ${{ github.ref == 'refs/heads/master' }}
          update_packager_index: false
          ccache_options: |
            max_size=1G

      - name: Install boost
        env:
          BOOST_MAJOR_VERSION: "1"
          BOOST_MINOR_VERSION: "77"
          BOOST_PATCH_VERSION: "0"
        run: |
          boost_url="https://archives.boost.io/release/${{ env.BOOST_MAJOR_VERSION }}.${{ env.BOOST_MINOR_VERSION }}.${{ env.BOOST_PATCH_VERSION }}/source/boost_${{ env.BOOST_MAJOR_VERSION }}_${{ env.BOOST_MINOR_VERSION }}_${{ env.BOOST_PATCH_VERSION }}.tar.gz"
          boost_url2="https://sourceforge.net/projects/boost/files/boost/${{ env.BOOST_MAJOR_VERSION }}.${{ env.BOOST_MINOR_VERSION }}.${{ env.BOOST_PATCH_VERSION }}/boost_${{ env.BOOST_MAJOR_VERSION }}_${{ env.BOOST_MINOR_VERSION }}_${{ env.BOOST_PATCH_VERSION }}.tar.gz"
          set +e
          curl -L -o "${{ runner.temp }}/boost.tar.gz" "$boost_url"
          tar -xf "${{ runner.temp }}/boost.tar.gz" -C "${{ github.workspace }}/.."; _exitCode="$?"
          if [ "$_exitCode" -ne "0" ]; then
            curl -L -o "${{ runner.temp }}/boost.tar.gz" "$boost_url2"
            tar -xf "${{ runner.temp }}/boost.tar.gz" -C "${{ github.workspace }}/.."; _exitCode="$?"
          fi
          mv "${{ github.workspace }}/.."/boost_* "${{ env.boost_path }}"
          cd "${{ env.boost_path }}"
          ./bootstrap.sh
          ./b2 stage --stagedir=./ --with-headers

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          archives: icu qtbase qtdeclarative qtsvg qttools
          cache: true

      - name: Install libtorrent
        run: |
          git clone \
            --branch v${{ matrix.libt_version }} \
            --depth 1 \
            --recurse-submodules \
            https://github.com/arvidn/libtorrent.git \
            ${{ env.libtorrent_path }}
          cd ${{ env.libtorrent_path }}
          CXXFLAGS="$CXXFLAGS ${{ env.harden_flags }}" \
          cmake \
            -B build \
            -G "Ninja" \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DBOOST_ROOT="${{ env.boost_path }}/lib/cmake" \
            -Ddeprecated-functions=OFF
          cmake --build build
          sudo cmake --install build

      # to avoid scanning 3rdparty codebases, initialize it just before building qbt
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        if: startsWith(matrix.libt_version, 2) && (matrix.qbt_gui == 'GUI=ON')
        with:
          config-file: ./.github/workflows/helper/codeql/cpp.yaml
          languages: cpp

      - name: Build qBittorrent
        run: |
          CXXFLAGS="$CXXFLAGS ${{ env.harden_flags }} -DQT_FORCE_ASSERTS -Werror" \
          LDFLAGS="$LDFLAGS -gz" \
          cmake \
            -B build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DBOOST_ROOT="${{ env.boost_path }}/lib/cmake" \
            -DCMAKE_INSTALL_PREFIX="/usr" \
            -DTESTING=ON \
            -DVERBOSE_CONFIGURE=ON \
            -D${{ matrix.qbt_gui }}
          cmake --build build --target qbt_update_translations
          cmake --build build
          cmake --build build --target check
          DESTDIR="qbittorrent" cmake --install build

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
        if: startsWith(matrix.libt_version, 2) && (matrix.qbt_gui == 'GUI=ON')
        with:
          category: ${{ github.base_ref || github.ref_name }}

      - name: Prepare build artifacts
        run: |
          mkdir upload
          mkdir upload/cmake
          cp build/compile_commands.json upload/cmake
          mkdir upload/cmake/libtorrent
          cp ${{ env.libtorrent_path }}/build/compile_commands.json upload/cmake/libtorrent

      - name: Install AppImage
        run: |
          curl \
            -L \
            -Z \
            -O https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${{ matrix.appimage_arch }}.AppImage \
            -O https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-${{ matrix.appimage_arch }}.AppImage \
            -O https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-${{ matrix.appimage_arch }}.AppImage
          chmod +x \
            linuxdeploy-${{ matrix.appimage_arch }}.AppImage \
            linuxdeploy-plugin-qt-${{ matrix.appimage_arch }}.AppImage \
            linuxdeploy-plugin-appimage-${{ matrix.appimage_arch }}.AppImage

      - name: Prepare files for AppImage
        if: matrix.qbt_gui == 'GUI=OFF'
        run: |
          mkdir -p qbittorrent/usr/share/applications
          cp .github/workflows/helper/appimage/org.qbittorrent.qBittorrent.desktop qbittorrent/usr/share/applications/org.qbittorrent.qBittorrent.desktop
          mkdir -p qbittorrent/usr/share/icons/hicolor/scalable/apps
          cp dist/unix/menuicons/scalable/apps/qbittorrent.svg qbittorrent/usr/share/icons/hicolor/scalable/apps/qbittorrent.svg

      - name: Package AppImage
        run: |
          rm -f "${{ runner.workspace }}/Qt/${{ matrix.qt_version }}/gcc/plugins/sqldrivers/libqsqlmimer.so"
          ./linuxdeploy-${{ matrix.appimage_arch }}.AppImage --appdir qbittorrent --plugin qt
          rm qbittorrent/apprun-hooks/*
          cp .github/workflows/helper/appimage/export_vars.sh qbittorrent/apprun-hooks/export_vars.sh
          NO_APPSTREAM=1 \
            OUTPUT=upload/qbittorrent-CI_Ubuntu_${{ matrix.appimage_arch }}.AppImage \
            ./linuxdeploy-${{ matrix.appimage_arch }}.AppImage --appdir qbittorrent --output appimage

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qBittorrent-CI_bookworm_x86_${{ matrix.qbt_gui }}_libtorrent-${{ matrix.libt_version }}_Qt-${{ matrix.qt_version }}
          path: upload
